In [1]:
import pandas as pd
import numpy as np
import os

# 1.Data Loading

In [2]:
df = pd.read_csv(r"F:\IMARTICUS\5. Machine Learning\LINEAR REGRESSSION\used_cars_dataset_v2.csv")

# 2.Exploratory Data Analysis

## 2.1 DATA UNDERSTANDING

In [3]:
df.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000"
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000"
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999"
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000"
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000"

In [4]:
df.tail()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
14988,Maruti Suzuki,Wagon-R,2022,2,"31,000 km",Manual,first,hybrid,Nov-24,"Maruti Suzuki Wagon R LXI CNG Optional, 2022, ...","₹ 5,75,000"
14989,BMW,X1,2017,7,"45,000 km",Automatic,second,Diesel,Dec-24,"BMW X1 2.0 SDRIVE 20D, 2017, Diesel","₹ 13,45,000"
14990,Maruti Suzuki,New-gen Swift,2011,13,"60,000 km",Automatic,second,Diesel,Nov-24,Bahut badhiya new condition,"₹ 1,60,000"
14991,Tata,Zest,2019,5,"62,000 km",Manual,second,hybrid,Nov-24,"Tata Zest Revotron 1.2T XE, 2019, CNG & Hybrids","₹ 3,80,000"
14992,Maruti Suzuki,Celerio,2019,5,"18,000 km",Manual,second,hybrid,Dec-24,"Maruti Suzuki Celerio CNG VXI MT, 2019, CNG & ...","₹ 4,50,000"

In [5]:
df.sample()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
14435,Volkswagen,VentoTest,2013,11,"87,615 km",Manual,second,Diesel,Nov-24,"Volkswagen Vento 1.6 Highline Plus 16 Alloy, 2...","₹ 4,25,000"

In [6]:
df.columns

Index(['Brand', 'model', 'Year', 'Age', 'kmDriven', 'Transmission', 'Owner',
       'FuelType', 'PostedDate', 'AdditionInfo', 'AskPrice'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14993 entries, 0 to 14992
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         14993 non-null  object
 1   model         14993 non-null  object
 2   Year          14993 non-null  int64
 3   Age           14993 non-null  int64
 4   kmDriven      14905 non-null  object
 5   Transmission  14993 non-null  object
 6   Owner         14993 non-null  object
 7   FuelType      14993 non-null  object
 8   PostedDate    14993 non-null  object
 9   AdditionInfo  14993 non-null  object
 10  AskPrice      14993 non-null  object
dtypes: int64(2), object(9)
memory usage: 1.3+ MB

In [8]:
df.shape

(14993, 11)

In [9]:
df.dtypes

Brand           object
model           object
Year             int64
Age              int64
kmDriven        object
Transmission    object
Owner           object
FuelType        object
PostedDate      object
AdditionInfo    object
AskPrice        object
dtype: object

## 2.2 Data Quality

In [10]:
df.isnull().sum()

Brand            0
model            0
Year             0
Age              0
kmDriven        88
Transmission     0
Owner            0
FuelType         0
PostedDate       0
AdditionInfo     0
AskPrice         0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(997)

In [12]:
df.nunique()

Brand              43
model             436
Year               36
Age                36
kmDriven         2718
Transmission        2
Owner               2
FuelType            4
PostedDate         13
AdditionInfo    10676
AskPrice         1616
dtype: int64

In [13]:
df.describe(percentiles=[0.01,0.02,0.03,0.04,0.05,0.50,0.90,0.95,0.96,0.97,0.98,0.99]).T

,count,mean,std,min,1%,2%,3%,4%,5%,50%,90%,95%,96%,97%,98%,99%,max
Year,14993.0,2016.32215,4.343017,1900.0,2006.0,2007.0,2008.0,2009.0,2009.0,2017.0,2022.0,2023.0,2023.0,2023.0,2023.0,2024.0,2024.0
Age,14993.0,7.67785,4.343017,0.0,0.0,1.0,1.0,1.0,1.0,7.0,13.0,15.0,15.0,16.0,17.0,18.0,124.0

# 3. DATA CLEANING

## 3.1Group-wise columns define

In [14]:
# Numerical columns
numerical_cols = ["Year", "Age", "kmDriven", "AskPrice"]

# Categorical columns
categorical_cols = ["Brand", "model", "Transmission", "Owner", "FuelType"]

# Date/Time columns
datetime_cols = ["PostedDate"]

# Text columns
text_cols = ["AdditionInfo"]

In [15]:
print("Numerical Columns:", numerical_cols)
print("Categorical Columns:", categorical_cols)
print("Date/Time Columns:", datetime_cols)
print("Text Columns:", text_cols)

Numerical Columns: ['Year', 'Age', 'kmDriven', 'AskPrice']
Categorical Columns: ['Brand', 'model', 'Transmission', 'Owner', 'FuelType']
Date/Time Columns: ['PostedDate']
Text Columns: ['AdditionInfo']

In [16]:
df[numerical_cols].dtypes

Year         int64
Age          int64
kmDriven    object
AskPrice    object
dtype: object

In [17]:
df[categorical_cols].dtypes

Brand           object
model           object
Transmission    object
Owner           object
FuelType        object
dtype: object

In [18]:
df[datetime_cols].dtypes

PostedDate    object
dtype: object

In [19]:
df[text_cols].dtypes

AdditionInfo    object
dtype: object

## 3.2 Data Types Treatment

In [20]:
df["kmDriven"] = (
    df["kmDriven"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("km", "", case=False, regex=False)
    .str.strip()
)

df["kmDriven"] = pd.to_numeric(df["kmDriven"], errors="coerce")

In [21]:
df["AskPrice"] = (
    df["AskPrice"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("₹", "", regex=False)
    .str.strip()
)

df["AskPrice"] = pd.to_numeric(df["AskPrice"], errors="coerce")

In [22]:
df["PostedDate"] = pd.to_datetime(
    df["PostedDate"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [23]:
df[["kmDriven", "AskPrice", "PostedDate"]].dtypes

kmDriven             float64
AskPrice               int64
PostedDate    datetime64[ns]
dtype: object

## 3.3 Missing values Treatment

In [24]:
df.isnull().sum()

Brand               0
model               0
Year                0
Age                 0
kmDriven           88
Transmission        0
Owner               0
FuelType            0
PostedDate      14993
AdditionInfo        0
AskPrice            0
dtype: int64

In [25]:
(df.isnull().sum() / len(df) * 100).round(2)

Brand             0.00
model             0.00
Year              0.00
Age               0.00
kmDriven          0.59
Transmission      0.00
Owner             0.00
FuelType          0.00
PostedDate      100.00
AdditionInfo      0.00
AskPrice          0.00
dtype: float64

In [26]:
missing = df.isnull().sum()

missing[missing > 0]

kmDriven         88
PostedDate    14993
dtype: int64

In [27]:
df["kmDriven"] = df["kmDriven"].fillna(df["kmDriven"].median())

In [28]:
df["kmDriven"].isnull().sum()

np.int64(0)

In [29]:
df.drop(columns=["PostedDate"], inplace=True)

In [30]:
df.columns

Index(['Brand', 'model', 'Year', 'Age', 'kmDriven', 'Transmission', 'Owner',
       'FuelType', 'AdditionInfo', 'AskPrice'],
      dtype='object')

## 3.4 Duplicate Values Treatment

In [31]:
df.duplicated().sum()

np.int64(1039)

In [32]:
df[df.duplicated()]

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,AdditionInfo,AskPrice
146,Audi,A3,2015,9,42000.0,Automatic,second,Diesel,"Audi A3 2.0 35 TDI Attraction, 2015, Diesel",1050000
152,Honda,City,2016,8,93000.0,Automatic,second,Petrol,Honda City 2016 Petrol Good Condition,575000
199,Audi,A3,2015,9,42000.0,Automatic,second,Diesel,"Audi A3 2.0 35 TDI Attraction, 2015, Diesel",1050000
221,Toyota,Camry,2015,9,68000.0,Automatic,second,Petrol,"Toyota Camry 2012-2014 Hybrid, 2015, Petrol",1185000
230,Mercedes-Benz,GLE COUPE,2021,3,32000.0,Automatic,second,Petrol,Mercedes-Benz GLE COUPE 3.0 53 AMG 4MATIC Plus...,11800000
...,...,...,...,...,...,...,...,...,...,...
14920,Toyota,Corolla Altis,2015,9,100000.0,Automatic,first,hybrid,"Toyota Corolla Altis 1.8 G CNG, 2015, CNG & Hy...",625000
14922,Ford,Endeavour,2016,8,91000.0,Manual,second,Diesel,"Ford Endeavour, 2016, Diesel",1890000
14960,Maruti Suzuki,Ignis,2021,3,46000.0,Manual,second,Petrol,Maruti Suzuki Ignis March 2021,599900
14980,Audi,A4,2013,11,98000.0,Automatic,second,Diesel,"Audi A4 2.0 TDI, 2013, Diesel",895000
14982,Maruti Suzuki,Wagon-R,2015,9,38000.0,Automatic,second,hybrid,"Maruti Suzuki Wagon R VXI AMT1.2, 2015, CNG & ...",350000

In [33]:
df.drop_duplicates(inplace=True)

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df[df.duplicated()]

Empty DataFrame
Columns: [Brand, model, Year, Age, kmDriven, Transmission, Owner, FuelType, AdditionInfo, AskPrice]
Index: []

## 3.5 Invalid & Inconsistent Numericals Values Treatment

In [36]:
df[df["Year"] < 1990]

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,AdditionInfo,AskPrice
7404,Maruti Suzuki,800,1986,38,68000.0,Manual,second,Petrol,Maruti Suzuki SS80,120000
11260,Maruti Suzuki,Wagon-R,1931,93,88000.0,Manual,first,hybrid,"Maruti Suzuki Wagon R 2010-2012 LXI BSIII, 193...",349000
11392,Renault,Triber,1900,124,40000.0,Automatic,second,hybrid,Renault Triber 11 12 2019 CNG & Hybrids 40000 ...,440000
11458,Mahindra,Jeep,1978,46,100000.0,Manual,second,Diesel,"Mahindra Jeep Classic, 1978, Diesel",200000
12545,Maruti Suzuki,Swift,1920,104,60000.0,Manual,first,Petrol,"Maruti Suzuki Swift 1.2 LXI (O), 1920, Petrol",519000

In [37]:
df[df["Age"] > 30]

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,AdditionInfo,AskPrice
1768,Mahindra,Jeep,1990,34,9000.0,Manual,second,Diesel,Mahindra Jeep 1990 Diesel,250000
7404,Maruti Suzuki,800,1986,38,68000.0,Manual,second,Petrol,Maruti Suzuki SS80,120000
11260,Maruti Suzuki,Wagon-R,1931,93,88000.0,Manual,first,hybrid,"Maruti Suzuki Wagon R 2010-2012 LXI BSIII, 193...",349000
11392,Renault,Triber,1900,124,40000.0,Automatic,second,hybrid,Renault Triber 11 12 2019 CNG & Hybrids 40000 ...,440000
11458,Mahindra,Jeep,1978,46,100000.0,Manual,second,Diesel,"Mahindra Jeep Classic, 1978, Diesel",200000
12545,Maruti Suzuki,Swift,1920,104,60000.0,Manual,first,Petrol,"Maruti Suzuki Swift 1.2 LXI (O), 1920, Petrol",519000

In [38]:
df["Year"].value_counts().sort_index()

Year
1900       1
1920       1
1931       1
1978       1
1986       1
1990       1
1994       3
1996       2
1997       2
1998       3
1999       5
2000       6
2001       9
2002       8
2003      18
2004      25
2005      55
2006      55
2007     116
2008     152
2009     256
2010     510
2011     635
2012     693
2013     752
2014     905
2015    1158
2016    1287
2017    1484
2018    1432
2019    1203
2020     813
2021     818
2022     790
2023     510
2024     243
Name: count, dtype: int64

In [39]:
df["Year"].min(), df["Year"].max()

(1900, 2024)

In [40]:
df["Year"].value_counts().sort_index().head(20)

Year
1900      1
1920      1
1931      1
1978      1
1986      1
1990      1
1994      3
1996      2
1997      2
1998      3
1999      5
2000      6
2001      9
2002      8
2003     18
2004     25
2005     55
2006     55
2007    116
2008    152
Name: count, dtype: int64

In [41]:
df[df["Year"] == 2011].shape

(635, 10)

In [42]:
df[df["Year"] < 1990][
    ["Brand", "model", "Year", "Age", "FuelType", "AdditionInfo", "AskPrice"]
]

,Brand,model,Year,Age,FuelType,AdditionInfo,AskPrice
7404,Maruti Suzuki,800,1986,38,Petrol,Maruti Suzuki SS80,120000
11260,Maruti Suzuki,Wagon-R,1931,93,hybrid,"Maruti Suzuki Wagon R 2010-2012 LXI BSIII, 193...",349000
11392,Renault,Triber,1900,124,hybrid,Renault Triber 11 12 2019 CNG & Hybrids 40000 ...,440000
11458,Mahindra,Jeep,1978,46,Diesel,"Mahindra Jeep Classic, 1978, Diesel",200000
12545,Maruti Suzuki,Swift,1920,104,Petrol,"Maruti Suzuki Swift 1.2 LXI (O), 1920, Petrol",519000

In [43]:
df = df[(df["Year"] >= 2011) & (df["Year"] <= 2024)].copy()

In [44]:
print(df["Year"].min())
print(df["Year"].max())

2011
2024

In [45]:
df["Year"].value_counts().sort_index()

Year
2011     635
2012     693
2013     752
2014     905
2015    1158
2016    1287
2017    1484
2018    1432
2019    1203
2020     813
2021     818
2022     790
2023     510
2024     243
Name: count, dtype: int64

In [46]:
df["Age"] = 2024 - df["Year"]

## 3.6 Inconsistent / Invalid Categorical Values

In [47]:
for col in ["Brand", "model", "Transmission", "Owner", "FuelType"]:
    print("\n", col)
    print(df[col].unique())

 Brand
['Maruti Suzuki' 'BMW' 'Toyota' 'Ford' 'Kia' 'Mercedes-Benz' 'Hyundai'
 'Audi' 'Renault' 'MG' 'Volvo' 'Volkswagen' 'Skoda' 'Honda' 'Mahindra'
 'Mini' 'Tata' 'Land Rover' 'Jeep' 'Chevrolet' 'Jaguar' 'Aston Martin'
 'Porsche' 'Nissan' 'Force' 'Fiat' 'Mitsubishi' 'Lexus' 'Isuzu' 'Datsun'
 'Ambassador' 'Rolls-Royce' 'Bajaj' 'Ashok' 'Bentley' 'Ssangyong'
 'Maserati' 'Toyota Land' 'Citroen' 'Lamborghini']

 model
['Swift' 'Baleno' 'X3' 'Innova' '5 Series' 'maruti-suzuki-dzire'
 'Ecosport' 'Alto-K10' 'Carnival' 'Swift-Dzire' 'GLE COUPE' 'Xcent'
 'Seltos' 'Ertiga' '3 Series GT' 'Endeavour' 'Innova Crysta' 'A3' 'KWID'
 'Hector' 'Celerio' 'Vitara-Brezza' '2.8 Legender 4X2' 'S90' 'Venue'
 'Creta' 'Alcazar' 'i20' 'E-Class' 'Polo' 'Verna' 'A4' 'Fortuner'
 'C-Class' 'Kushaq' 'Ciaz' 'BRV' 'Duster' 'Wagon-R' 'Bolero Power Plus'
 'Eon' 'Hector Plus' 'XUV500' 'GLS' 'i10' 'GLA Class' 'Carens' 'Ignis'
 'Grand i10' 'City' 'Ritz' 'Sonet' 'GLC Coupe' 'Scorpio-N' 'Cooper 3 DOOR'
 'Nexon' 'Etios' 'CrossPolo' 'Vento' 'Range Rover Evoque' 'Indigo Ecs'
 'Thar' 'Camry' 'Bolero' 'Brio' 'WRV' 'Discovery Sport' 'Harrier' 'Zest'
 'Eeco' 'Swift Dzire' 'VentoTest' 'Kodiaq' 'Altroz' 'Grand i10 Nios'
 'Alto-800' 'X1' 'X5' 'Rapid' 'TUV' 'Alto K10' 'M-Class' 'Glanza'
 'Compass' 'Cruze' 'Amaze' 'Jazz' 'Scala' 'S-Presso' 'Tucson' 'Alto'
 'Santa Fe' 'Dzire' 'ASTOR' 'Q7' 'Cooper 5 DOOR' 'Q3' 'Hexa'
 'Creta Facelift' '7 Series' 'Bolt' 'XF' 'Tiago' 'Safari' 'Nano Genx'
 'City Hybrid eHEV' 'Tiguan' 'G' '3 Series' 'Range Rover' 'Grand Vitara'
 'XC 90' 'A6' 'Polo GTI' 'Virtus' 'A-Star' 'Cooper S' 'Etios Liva' 'CLA'
 'XUV700' 'Alturas G4' 'Scorpio' 'New i20' 'Alto 800' 'Elite i20' 'Omni'
 'Defender' 'Vanquish' 'maruti-suzuki-brezza' 'A8 L' 'V40 Cross Country'
 'Captur' 'Passat' 'KUV 100' 'Bolero Neo' 'Elantra' 'Macan' 'Terrano'
 'XL6' 'S-Class' '6 Series GT' 'Figo' 'City ZX' 'Ameo' 'Innova Hycross'
 'Triber' 'Q5' 'Motors FM Gurkha' '718' 'Punto' 'Corolla Altis'
 'Pajero Sport' 'Manza' 'Cooper Convertible' 'Scorpio Classic' 'ES' 'Sx4'
 'GL-Class' 'Tigor' 'X7' 'Octavia' 'Wagon R' 'S-Cross' 'Boxster' 'XC40'
 'Lodgy' 'Nano' 'XC60' 'Z4' 'Civic' 'Urban Cruiser' 'Brezza' 'Punch' 'GLC'
 'Sonata Embera' 'CRV' 'Figo Aspire' '3 DOOR' 'MAX' 'G Class' 'RediGO'
 'CLS-Class' 'Xylo' 'VELLFIRE' 'Superb' 'Cooper' 'X4' 'LX' 'Enjoy'
 'Mobilio' 'Punto EVO' 'Bolero Neo Plus' 'Scorpio N' 'D-Max V-Cross'
 'Fluidic Verna' 'G-Class' 'XUV 300' ' Wagon R' 'Cooper Countryman' 'GLE'
 'GLC Class' 'Fiesta Classic' 'MUX' 'V-Class' 'Safari Storme' 'Indica Ev2'
 'Celerio-X' 'Land Cruiser' 'Corolla' 'Indica' 'MICRA PRIMO' 'Indigo Cs'
 'S-Cross1' 'S60 Cross Country' 'Slavia' 'Punch ' '1000' 'XJ' 'Fronx'
 'Beat' 'S60' 'Cayenne' 'Range Rover Sport' 'Verito' 'WR-V' 'Laura'
 'Range Rover Velar' 'Jetta' 'Freelander 2' 'Discovery' 'Micra' 'Kiger'
 'Ambassador' 'Marazzo' 'i20 Active' 'Redi Go' '2 Series' '800'
 'Etios Cross' 'GLA' 'GLE Class' 'Swift-Dzire-Tour' 'A5' 'Jimny'
 'Santro Xing' 'AMG GLE Coupe' 'Countryman' 'Sail U-VA' 'Fluence' 'NX'
 'Fiesta' 'Pulse' 'Santro' 'Sonata' 'Wagon-R-1-0' 'Tiago Nrg' '1 Series'
 'S 80' 'Aura' '6 Series' 'Meridian' 'Kicks' 'Vitara Brezza'
 '3 Series Gran Limousine' 'PATROL' 'B Class' 'TUV 300' 'Sail' 'Yaris'
 'Sumo Grande MK II' 'S80' 'Celerio X' 'EON' 'Motors FM Trax Cruiser'
 'XUV300' 'Sunny' 'Sumo Gold' 'X6' 'Magnite' 'KUV100 NXT' 'Gloster'
 'Urban Cruiser Hyryder' 'Trailblazer' 'Quanto' 'Sumo Victa'
 'Indica Vista' 'i20 N Line' 'Xenon XT' 'Land Cruiser Prado' 'Taigun'
 'Zen Estilo' 'Cooper Clubman' 'A-Class Limousine' 'XE' 'Venue N Line'
 'tata-punch' 'Cayenne Coupe' 'F-Pace' 'GO' 'Phantom Series II' 'Fabia'
 'Linea' 'Accord' 'Venture' 'Aspire' 'LS' 'Mustang' 'Tiguan All Space'
 'Free Style' 'H5x' 'XC90' 'C Class' 'TUV 300-plus' 'Wagon R 1.0'
 'AMG C 43' 'Accent' 'Estilo' 'CR-V' 'New Elantra' 'Zen-Estilo'
 'Motors FM Force One Test' 'New-gen Swift' 'Spark' 'Punto Pure' 'RX'
 'Xcent Prime' 'E-20' 'New Duster' 'Ssangyong-Rexton' 'Grand i10 Prime'
 'Wrangler' 'SLK-Class' 'RE60' 'Phantom Drop HeadCoupe' 'Nuvosport'
 'Indica V2' 'Panamera' 'Wagon-R-Stingray' '5 DOOR' 'Micra Active'
 'New Santro' 'Cayman' 'AMG A35' 'Optra Magnum' 'M340i' 'GTI' 'X5 M'
 'Baleno-RS' 'A Class' 'Exter' 'Invicto' 'Rexton' 'Stingray' 'Gypsy'
 'Fronx ' 'SL-Class' 'Vista Tech' 'Captiva' 'GO Plus' 'A3 Cabriolet'
 'Leyland Stile' 'Flying Spur' 'Tavera' 'Outlander' 'Curvv' 'Estima'
 'Avventura' 'Others' 'Grand Punto' 'Ssangyong Rexton' 'A-class Limousine'
 '2.9 Sportback' 'CERATO' 'Elevate' 'Urvan' 'Hi-Lande Isuzu Hi-Lander'
 'AMG' 'Urban Cross' 'Gran Turismo' 'M2' 'Verito Vibe' 'Aria' 'New Verna'
 '5 Series Gt' 'Cruiser' 'Grande Punto' 'MU-X' 'Karoq' 'Q3 Sportback'
 'Thar Roxx' 'Escort' 'Jeep' 'Maxx' 'Five-door Thar' 'C5 Aircross'
 'Cruiser Prado' 'Pajero' 'S Cross' 'RS7' 'Punch EV' 'Urus' 'XUV 3XO'
 'Harrier EV' '718 CAYMAN' 'Teana' 'Q2' 'R-Class' 'Imperio' 'A8' 'T-ROC'
 'X-Trail' 'Yeti' 'Indigo Marina']

 Transmission
['Manual' 'Automatic']

 Owner
['second' 'first']

 FuelType
['Diesel' 'Petrol' 'Hybrid/CNG' 'hybrid']

In [48]:
df[df["FuelType"] == "hybrid"][["Brand", "model", "Year", "FuelType", "AskPrice"]]

               Brand        model  Year FuelType  AskPrice
9582         Hyundai  Xcent Prime  2019   hybrid    420000
9583   Maruti Suzuki      Wagon-R  2014   hybrid    210000
9584   Maruti Suzuki      Wagon-R  2014   hybrid    350000
9585            Tata        Tigor  2023   hybrid    720000
9589   Maruti Suzuki       Ertiga  2018   hybrid    735000
...              ...          ...   ...      ...       ...
14984  Maruti Suzuki       Ertiga  2016   hybrid    625000
14985  Maruti Suzuki         Eeco  2015   hybrid    300000
14988  Maruti Suzuki      Wagon-R  2022   hybrid    575000
14991           Tata         Zest  2019   hybrid    380000
14992  Maruti Suzuki      Celerio  2019   hybrid    450000

[1705 rows x 5 columns]

In [49]:
df[df["FuelType"] == "hybrid"][["Brand", "model", "Year", "FuelType", "AskPrice"]].head(20)

              Brand        model  Year FuelType  AskPrice
9582        Hyundai  Xcent Prime  2019   hybrid    420000
9583  Maruti Suzuki      Wagon-R  2014   hybrid    210000
9584  Maruti Suzuki      Wagon-R  2014   hybrid    350000
9585           Tata        Tigor  2023   hybrid    720000
9589  Maruti Suzuki       Ertiga  2018   hybrid    735000
9590        Hyundai          i10  2012   hybrid    165000
9591  Maruti Suzuki       Ertiga  2022   hybrid   1200000
9600  Maruti Suzuki  Swift-Dzire  2017   hybrid    490000
9601  Maruti Suzuki    Celerio-X  2019   hybrid    425000
9608  Maruti Suzuki      Celerio  2022   hybrid    525180
9613        Hyundai       Accent  2011   hybrid     85000
9615  Maruti Suzuki       Baleno  2017   hybrid    525000
9616        Hyundai  Santro Xing  2012   hybrid    175000
9620        Hyundai       Santro  2018   hybrid    450000
9622         Datsun      Redi Go  2016   hybrid    178000
9623  Maruti Suzuki       Ertiga  2023   hybrid   1240000
9629  Maruti Suzuki  Swift-Dzire  2023   hybrid    580000
9630        Hyundai    Grand i10  2016   hybrid    375000
9634        Hyundai       Santro  2012   hybrid    160000
9635        Renault       Triber  2020   hybrid    385000

In [50]:
df["FuelType"].value_counts()

FuelType
Petrol        4783
Diesel        4618
hybrid        1705
Hybrid/CNG    1617
Name: count, dtype: int64

In [51]:
df["Brand"].value_counts()

Brand
Maruti Suzuki    3972
Hyundai          2058
Honda             967
Toyota            961
Mahindra          681
Tata              539
Mercedes-Benz     495
Volkswagen        428
BMW               363
Renault           355
Ford              349
Audi              277
Skoda             249
Kia               209
MG                107
Nissan            105
Land Rover         97
Jeep               95
Chevrolet          84
Volvo              62
Datsun             49
Jaguar             47
Mini               40
Lexus              28
Porsche            27
Fiat               22
Mitsubishi         15
Isuzu              13
Force               7
Ssangyong           5
Toyota Land         3
Bajaj               3
Citroen             2
Rolls-Royce         2
Ambassador          2
Bentley             1
Ashok               1
Maserati            1
Aston Martin        1
Lamborghini         1
Name: count, dtype: int64

In [52]:
df[df["Brand"] == "Toyota Land"][["Brand", "model", "Year", "FuelType", "AskPrice"]]

             Brand          model  Year FuelType  AskPrice
11006  Toyota Land        Cruiser  2013   Diesel   8200000
11534  Toyota Land        Cruiser  2017   Diesel  16500000
12324  Toyota Land  Cruiser Prado  2012   Diesel   3200000

In [53]:
df.loc[df["Brand"] == "Toyota Land", "Brand"] = "Toyota"

In [54]:
df["Brand"].value_counts()

Brand
Maruti Suzuki    3972
Hyundai          2058
Honda             967
Toyota            964
Mahindra          681
Tata              539
Mercedes-Benz     495
Volkswagen        428
BMW               363
Renault           355
Ford              349
Audi              277
Skoda             249
Kia               209
MG                107
Nissan            105
Land Rover         97
Jeep               95
Chevrolet          84
Volvo              62
Datsun             49
Jaguar             47
Mini               40
Lexus              28
Porsche            27
Fiat               22
Mitsubishi         15
Isuzu              13
Force               7
Ssangyong           5
Bajaj               3
Ambassador          2
Rolls-Royce         2
Citroen             2
Aston Martin        1
Ashok               1
Bentley             1
Maserati            1
Lamborghini         1
Name: count, dtype: int64

In [55]:
df[df["Brand"] == "Toyota Land"][["Brand", "model", "Year", "FuelType", "AskPrice"]]

Empty DataFrame
Columns: [Brand, model, Year, FuelType, AskPrice]
Index: []

In [56]:
df["model"] = df["model"].str.strip()

In [57]:
df["model"].value_counts()

model
Wagon-R          527
City             426
Ertiga           422
Swift            342
Swift-Dzire      339
                ...
AMG A35            1
5 DOOR             1
G                  1
G-Class            1
Indigo Marina      1
Name: count, Length: 410, dtype: int64

In [58]:
df[df["model"].str.contains(r"^\s|\s$", regex=True, na=False)]["model"].unique()

array([], dtype=object)

In [59]:
df["model_check"] = (
    df["model"]
    .str.lower()
    .str.replace("-", "", regex=False)
    .str.replace(" ", "", regex=False)
)

In [60]:
df.groupby("model_check")["model"].unique()

model_check
1000                                [1000]
1series                         [1 Series]
2.8legender4x2          [2.8 Legender 4X2]
2.9sportback               [2.9 Sportback]
2series                         [2 Series]
                            ...
yaris                              [Yaris]
yeti                                [Yeti]
z4                                    [Z4]
zenestilo         [Zen Estilo, Zen-Estilo]
zest                                [Zest]
Name: model, Length: 389, dtype: object

In [61]:
duplicate_model_groups = (
    df.groupby("model_check")["model"]
    .unique()
)

duplicate_model_groups[
    duplicate_model_groups.apply(len) > 1
]

model_check
aclasslimousine    [A-Class Limousine, A-class Limousine]
alto800                              [Alto-800, Alto 800]
altok10                              [Alto-K10, Alto K10]
cclass                                 [C-Class, C Class]
celeriox                           [Celerio-X, Celerio X]
crv                                           [CRV, CR-V]
eon                                            [Eon, EON]
gclass                                 [G Class, G-Class]
mux                                           [MUX, MU-X]
redigo                                  [RediGO, Redi Go]
s80                                           [S 80, S80]
scorpion                           [Scorpio-N, Scorpio N]
scross                                 [S-Cross, S Cross]
ssangyongrexton      [Ssangyong-Rexton, Ssangyong Rexton]
swiftdzire                     [Swift-Dzire, Swift Dzire]
vitarabrezza               [Vitara-Brezza, Vitara Brezza]
wagonr                                 [Wagon-R, Wagon R]
wrv                                           [WRV, WR-V]
xc90                                        [XC 90, XC90]
xuv300                                  [XUV 300, XUV300]
zenestilo                        [Zen Estilo, Zen-Estilo]
Name: model, dtype: object

In [62]:
model_mapping = {
    "A-class Limousine": "A-Class Limousine",
    "Alto-800": "Alto 800",
    "Alto-K10": "Alto K10",
    "C Class": "C-Class",
    "Celerio X": "Celerio-X",
    "CRV": "CR-V",
    "EON": "Eon",
    "G Class": "G-Class",
    "MUX": "MU-X",
    "RediGO": "Redi Go",
    "S 80": "S80",
    "Scorpio-N": "Scorpio N",
    "S Cross": "S-Cross",
    "Ssangyong-Rexton": "Ssangyong Rexton",
    "Swift-Dzire": "Swift Dzire",
    "Vitara-Brezza": "Vitara Brezza",
    "Wagon-R": "Wagon R",
    "WRV": "WR-V",
    "XC 90": "XC90",
    "XUV 300": "XUV300",
    "Zen-Estilo": "Zen Estilo"
}

df["model"] = df["model"].replace(model_mapping)

In [63]:
df["model"].nunique()

389

In [64]:
df.groupby("model_check")["model"].unique().apply(lambda x: x if len(x) > 1 else None).dropna()

Series([], Name: model, dtype: object)

In [65]:
df["model"].value_counts()

model
Wagon R          571
City             426
Ertiga           422
Swift Dzire      359
Swift            342
                ...
Gypsy              1
G                  1
Vanquish           1
718                1
Indigo Marina      1
Name: count, Length: 389, dtype: int64

In [66]:
df[df["model"].isin([
    "VentoTest",
    "S-Cross1",
    "Motors FM Force One Test"
])][
    ["Brand", "model", "Year", "FuelType", "AskPrice"]
]

            Brand      model  Year FuelType  AskPrice
124    Volkswagen  VentoTest  2016   Petrol    555000
190    Volkswagen  VentoTest  2013   Petrol    292000
195    Volkswagen  VentoTest  2019   Diesel    695000
229    Volkswagen  VentoTest  2016   Petrol    525000
235    Volkswagen  VentoTest  2018   Diesel    775000
...           ...        ...   ...      ...       ...
14153  Volkswagen  VentoTest  2011   Diesel    330000
14214  Volkswagen  VentoTest  2011   Petrol    250000
14435  Volkswagen  VentoTest  2013   Diesel    425000
14624  Volkswagen  VentoTest  2019   Petrol    719000
14717  Volkswagen  VentoTest  2018   Diesel    690000

[122 rows x 5 columns]

In [67]:
df.loc[df["model"] == "VentoTest", "model"] = "Vento"

In [68]:
print("Vento:", (df["model"] == "Vento").sum())
print("VentoTest:", (df["model"] == "VentoTest").sum())

Vento: 130
VentoTest: 0

In [69]:
df[df["model"] == "S-Cross1"][
    ["Brand", "model", "Year", "FuelType", "AskPrice"]
]

               Brand     model  Year FuelType  AskPrice
1225   Maruti Suzuki  S-Cross1  2021   Petrol    750000
1250   Maruti Suzuki  S-Cross1  2018   Diesel    849000
1524   Maruti Suzuki  S-Cross1  2018   Diesel    530000
1843   Maruti Suzuki  S-Cross1  2018   Diesel    610000
3139   Maruti Suzuki  S-Cross1  2018   Diesel    650000
4242   Maruti Suzuki  S-Cross1  2017   Diesel    499999
7546   Maruti Suzuki  S-Cross1  2018   Diesel    715999
8011   Maruti Suzuki  S-Cross1  2018   Diesel    525000
9555   Maruti Suzuki  S-Cross1  2017   Diesel    745000
10735  Maruti Suzuki  S-Cross1  2016   Diesel    590000
11065  Maruti Suzuki  S-Cross1  2018   Diesel    580000
12553  Maruti Suzuki  S-Cross1  2021   Petrol    699999

In [70]:
df.loc[df["model"] == "S-Cross1", "model"] = "S-Cross"

In [71]:
print("S-Cross:", (df["model"] == "S-Cross").sum())
print("S-Cross1:", (df["model"] == "S-Cross1").sum())

S-Cross: 35
S-Cross1: 0

In [72]:
df[df["model"] == "Motors FM Force One Test"][
    ["Brand", "model", "Year", "FuelType", "AskPrice"]
]

      Brand                     model  Year    FuelType  AskPrice
4097  Force  Motors FM Force One Test  2016  Hybrid/CNG    560000
8166  Force  Motors FM Force One Test  2016  Hybrid/CNG    560000

In [73]:
df.loc[
    df["model"] == "Motors FM Force One Test",
    "model"
] = "Force One"

In [74]:
print("Force One:", (df["model"] == "Force One").sum())
print("Motors FM Force One Test:", 
      (df["model"] == "Motors FM Force One Test").sum())

Force One: 2
Motors FM Force One Test: 0

In [75]:
df["model"].value_counts().sort_values().head(50)

model
Indigo Marina               1
T-ROC                       1
A8                          1
Imperio                     1
R-Class                     1
Q2                          1
Teana                       1
Harrier EV                  1
Maxx                        1
XUV 3XO                     1
Urus                        1
Punch EV                    1
RS7                         1
Xenon XT                    1
Cruiser Prado               1
Land Cruiser Prado          1
X-Trail                     1
Yeti                        1
718 CAYMAN                  1
Jeep                        1
M2                          1
Karoq                       1
Urvan                       1
Thar Roxx                   1
Hi-Lande Isuzu Hi-Lander    1
Sumo Gold                   1
AMG                         1
CERATO                      1
Urban Cross                 1
Gran Turismo                1
Cooper Clubman              1
Escort                      1
New Verna                   1
Aria                        1
5 Series Gt                 1
Five-door Thar              1
Verito Vibe                 1
Sumo Grande MK II           1
718                         1
2.9 Sportback               1
Leyland Stile               1
Others                      1
Avventura                   1
A5                          1
Outlander                   1
Tavera                      1
Flying Spur                 1
Grand Punto                 1
A3 Cabriolet                1
GLC Coupe                   1
Name: count, dtype: int64

In [76]:
df[df["model"].isin(["Cruiser Prado", "Land Cruiser Prado"])][
    ["Brand", "model", "Year", "FuelType", "AskPrice"]
]

        Brand               model  Year FuelType  AskPrice
2851   Toyota  Land Cruiser Prado  2014   Diesel   4750000
12324  Toyota       Cruiser Prado  2012   Diesel   3200000

In [77]:
df.loc[df["model"] == "Cruiser Prado", "model"] = "Land Cruiser Prado"

In [78]:
df[df["model"] == "Land Cruiser Prado"][
    ["Brand", "model", "Year", "FuelType", "AskPrice"]
]

        Brand               model  Year FuelType  AskPrice
2851   Toyota  Land Cruiser Prado  2014   Diesel   4750000
12324  Toyota  Land Cruiser Prado  2012   Diesel   3200000

In [79]:
df[df["model"] == "Jeep"][
    ["Brand", "model", "Year", "FuelType", "AskPrice"]
]

          Brand model  Year FuelType  AskPrice
12127  Mahindra  Jeep  2012   Diesel    550000

In [80]:
df[df["Brand"] == "Mahindra"]["model"].value_counts()

model
XUV500               184
Thar                 105
Scorpio               82
Bolero                52
XUV300                37
TUV                   27
Marazzo               25
Xylo                  24
XUV700                21
KUV 100               19
Scorpio N             18
Scorpio Classic       15
Bolero Neo            10
Bolero Power Plus      9
KUV100 NXT             8
Ssangyong Rexton       7
Alturas G4             7
Verito                 7
Quanto                 4
Bolero Neo Plus        3
Rexton                 3
Nuvosport              3
TUV 300                2
E-20                   1
TUV 300-plus           1
Verito Vibe            1
Thar Roxx              1
Jeep                   1
Maxx                   1
Five-door Thar         1
XUV 3XO                1
Imperio                1
Name: count, dtype: int64

In [81]:
df[df["model"] == "AMG"][
    ["Brand", "model", "Year", "FuelType", "AskPrice"]
]

              Brand model  Year FuelType  AskPrice
9241  Mercedes-Benz   AMG  2024   Petrol  21500000

In [82]:
df[df["model"] == "Escort"][
    ["Brand", "model", "Year", "FuelType", "AskPrice"]
]

      Brand   model  Year FuelType  AskPrice
11953  Ford  Escort  2015   Diesel    389000

In [83]:
df[df["Brand"] == "Ford"]["model"].value_counts()

model
Ecosport          158
Endeavour          92
Figo               48
Figo Aspire        18
Aspire             12
Fiesta              7
Mustang             5
Free Style          5
Fiesta Classic      3
Escort              1
Name: count, dtype: int64

In [84]:
df[df["model"] == "New Verna"][
    ["Brand", "model", "Year", "FuelType", "AskPrice"]
]

         Brand      model  Year FuelType  AskPrice
10761  Hyundai  New Verna  2023   Petrol   1400000

In [85]:
df["model"].value_counts().sort_values().head(50)

model
Indigo Marina               1
X-Trail                     1
T-ROC                       1
A8                          1
Imperio                     1
R-Class                     1
Q2                          1
Teana                       1
718 CAYMAN                  1
Harrier EV                  1
XUV 3XO                     1
Urus                        1
Punch EV                    1
RS7                         1
Xenon XT                    1
Five-door Thar              1
Yeti                        1
2.9 Sportback               1
Jeep                        1
Maxx                        1
M2                          1
AMG                         1
Sumo Grande MK II           1
Sumo Gold                   1
Urvan                       1
Hi-Lande Isuzu Hi-Lander    1
Karoq                       1
Urban Cross                 1
Verito Vibe                 1
Cooper Clubman              1
5 Series Gt                 1
Gran Turismo                1
Thar Roxx                   1
Aria                        1
New Verna                   1
Escort                      1
CERATO                      1
718                         1
Grand Punto                 1
X5 M                        1
Avventura                   1
Estima                      1
A5                          1
Tavera                      1
Flying Spur                 1
Leyland Stile               1
A3 Cabriolet                1
GLC Coupe                   1
Captiva                     1
SL-Class                    1
Name: count, dtype: int64

In [86]:
rare_models = df["model"].value_counts()
rare_models = rare_models[rare_models == 1]

print(rare_models)

model
M2                   1
AMG                  1
Sumo Grande MK II    1
Sumo Gold            1
Urvan                1
                    ..
Gypsy                1
G                    1
Vanquish             1
718                  1
Indigo Marina        1
Name: count, Length: 75, dtype: int64

In [87]:
rare_model_list = rare_models.index

df[df["model"].isin(rare_model_list)][
    ["Brand", "model", "Year", "FuelType", "AskPrice"]
].sort_values(["Brand", "model"])

              Brand          model  Year    FuelType  AskPrice
7507          Ashok  Leyland Stile  2024  Hybrid/CNG     32000
331    Aston Martin       Vanquish  2016      Petrol  26400000
8604           Audi  2.9 Sportback  2018      Petrol   7500000
7505           Audi   A3 Cabriolet  2016      Petrol   2899999
1780           Audi             A5  2011      Diesel   1275000
...             ...            ...   ...         ...       ...
2823           Tata       Xenon XT  2017      Diesel    510000
1188         Toyota        Corolla  2014      Petrol    160000
7807         Toyota         Estima  2012      Petrol   2300000
5601     Volkswagen            GTI  2016      Petrol    530000
14365    Volkswagen          T-ROC  2020      Petrol   1149999

[75 rows x 5 columns]

In [88]:
suspect_models = df[
    df["model"].str.contains(
        r"test|others|^1000$|^800$|^3 DOOR$|^5 DOOR$",
        case=False,
        regex=True,
        na=False
    )
]

suspect_models[
    ["Brand", "model", "Year", "FuelType", "AskPrice"]
]

               Brand   model  Year    FuelType  AskPrice
801             Mini  3 DOOR  2015      Diesel   2000000
931             Mini  3 DOOR  2019      Petrol   3900000
1232   Maruti Suzuki    1000  2020      Diesel    390000
1652   Maruti Suzuki     800  2014      Petrol    240000
2146   Maruti Suzuki     800  2014      Petrol    180000
2234   Maruti Suzuki     800  2012      Petrol    120000
3689   Maruti Suzuki     800  2013      Petrol     50000
5323            Mini  5 DOOR  2015      Diesel   2700000
7816   Maruti Suzuki    1000  2023  Hybrid/CNG    400000
7940          Jaguar  Others  2014      Diesel   2250000
8098   Maruti Suzuki     800  2016  Hybrid/CNG    200000
11134  Maruti Suzuki     800  2014      hybrid    170000
12598  Maruti Suzuki     800  2015      hybrid    230000
13880  Maruti Suzuki     800  2012      Diesel    140000

In [89]:
df[df["model"].str.contains(
    "test|others",
    case=False,
    na=False
)][["Brand", "model", "Year", "FuelType", "AskPrice"]]

       Brand   model  Year FuelType  AskPrice
7940  Jaguar  Others  2014   Diesel   2250000

In [90]:
df = df[df["model"].str.lower() != "others"].copy()

In [91]:
df[df["model"].str.lower() == "others"]

Empty DataFrame
Columns: [Brand, model, Year, Age, kmDriven, Transmission, Owner, FuelType, AdditionInfo, AskPrice, model_check]
Index: []

In [92]:
df[df["model"].isin(["1000", "800"])][
    ["Brand", "model", "Year", "FuelType", "AskPrice"]
].sort_values(["model", "Year"])

               Brand model  Year    FuelType  AskPrice
1232   Maruti Suzuki  1000  2020      Diesel    390000
7816   Maruti Suzuki  1000  2023  Hybrid/CNG    400000
2234   Maruti Suzuki   800  2012      Petrol    120000
13880  Maruti Suzuki   800  2012      Diesel    140000
3689   Maruti Suzuki   800  2013      Petrol     50000
1652   Maruti Suzuki   800  2014      Petrol    240000
2146   Maruti Suzuki   800  2014      Petrol    180000
11134  Maruti Suzuki   800  2014      hybrid    170000
12598  Maruti Suzuki   800  2015      hybrid    230000
8098   Maruti Suzuki   800  2016  Hybrid/CNG    200000

In [93]:
model_mapping = {
    "VentoTest": "Vento",
    "S-Cross1": "S-Cross",
    "Motors FM Force One Test": "Force One",
    "Cruiser Prado": "Land Cruiser Prado",
    "800": "Maruti 800"
}

df["model"] = df["model"].replace(model_mapping)

df = df[df["model"].str.lower() != "others"].copy()

df = df[df["model"] != "1000"].copy()

In [94]:
print(df.shape)
print(df["model"].nunique())

print("\nSuspicious values:")
print(
    df[df["model"].str.contains(
        r"test|others|^1000$|^800$",
        case=False,
        regex=True,
        na=False
    )]["model"].value_counts()
)

(12720, 11)
384

Suspicious values:
Series([], Name: count, dtype: int64)

In [95]:
# 1. Numeric columns check
print("Year range:")
print(df["Year"].min(), df["Year"].max())

print("\nAge range:")
print(df["Age"].min(), df["Age"].max())

print("\nkmDriven range:")
print(df["kmDriven"].min(), df["kmDriven"].max())

print("\nAskPrice range:")
print(df["AskPrice"].min(), df["AskPrice"].max())


# 2. Negative values check
print("\nNegative values:")
print("Year:", (df["Year"] < 0).sum())
print("Age:", (df["Age"] < 0).sum())
print("kmDriven:", (df["kmDriven"] < 0).sum())
print("AskPrice:", (df["AskPrice"] < 0).sum())


# 3. Categorical missing values
print("\nCategorical missing values:")
print(df[["Brand", "model", "Transmission", "Owner", "FuelType"]].isnull().sum())


# 4. Suspicious model names — batch check
print("\nSuspicious model values:")
print(
    df[
        df["model"].str.contains(
            r"test|others|unknown|^1000$|^800$|door",
            case=False,
            regex=True,
            na=False
        )
    ][["Brand", "model", "Year", "FuelType", "AskPrice"]]
)

Year range:
2011 2024

Age range:
0 13

kmDriven range:
0.0 980002.0

AskPrice range:
15000 42500000

Negative values:
Year: 0
Age: 0
kmDriven: 0
AskPrice: 0

Categorical missing values:
Brand           0
model           0
Transmission    0
Owner           0
FuelType        0
dtype: int64

Suspicious model values:
          Brand           model  Year FuelType  AskPrice
83         Mini   Cooper 3 DOOR  2019   Petrol   3950000
233        Mini   Cooper 5 DOOR  2014   Diesel   1900000
407        Mini   Cooper 3 DOOR  2020   Petrol   4450000
801        Mini          3 DOOR  2015   Diesel   2000000
931        Mini          3 DOOR  2019   Petrol   3900000
2568       Mini   Cooper 5 DOOR  2014   Diesel   1695000
3396       Mini   Cooper 3 DOOR  2021   Petrol   5200000
5296       Mini   Cooper 3 DOOR  2015   Diesel   2000000
5323       Mini          5 DOOR  2015   Diesel   2700000
9712       Mini   Cooper 3 DOOR  2016   Petrol   2325000
12288  Mahindra  Five-door Thar  2024   Diesel   2550000

In [96]:
print("Highest kmDriven:")
print(
    df.nlargest(20, "kmDriven")
    [["Brand", "model", "Year", "kmDriven", "FuelType", "AskPrice"]]
)

print("\nHighest AskPrice:")
print(
    df.nlargest(20, "AskPrice")
    [["Brand", "model", "Year", "kmDriven", "FuelType", "AskPrice"]]
)

print("\nLowest AskPrice:")
print(
    df.nsmallest(20, "AskPrice")
    [["Brand", "model", "Year", "kmDriven", "FuelType", "AskPrice"]]
)

Highest kmDriven:
               Brand             model  Year  kmDriven    FuelType  AskPrice
6678      Volkswagen              Polo  2019  980002.0      Petrol    675000
4768   Maruti Suzuki          Alto 800  2019  980000.0  Hybrid/CNG    310000
7738       Chevrolet             Cruze  2012  950000.0      Diesel    350000
13263        Hyundai            Accent  2011  950000.0      Petrol    140000
14911          Honda             Amaze  2018  950000.0      hybrid    320000
11449  Maruti Suzuki  Swift-Dzire-Tour  2022  901500.0      hybrid    690000
13114  Maruti Suzuki              Eeco  2019  900000.0      hybrid    345000
2222   Mercedes-Benz         GLE Class  2016  850000.0      Diesel   2600000
3267      Mitsubishi      Pajero Sport  2015  850000.0      Diesel    875000
9411           Honda             Amaze  2013  850000.0  Hybrid/CNG    450000
10890  Maruti Suzuki              Alto  2012  820002.0      hybrid    110000
8982   Maruti Suzuki          S-Presso  2020  801270.0  Hybrid/CNG    465000
10669  Maruti Suzuki          S-Presso  2020  801270.0      hybrid    465000
595             Tata             Tigor  2018  800000.0      Petrol    485000
9313   Maruti Suzuki           Wagon R  2020  800000.0  Hybrid/CNG    535000
10882  Maruti Suzuki           Wagon R  2020  800000.0      hybrid    535000
14979        Hyundai               Eon  2012  781313.0      Petrol    155000
7277   Maruti Suzuki            Ertiga  2020  780000.0  Hybrid/CNG    949999
13188  Maruti Suzuki       Swift Dzire  2022  780000.0      hybrid    760000
1387            Tata             Nexon  2020  775000.0      Diesel    895000

Highest AskPrice:
               Brand              model  Year  kmDriven FuelType  AskPrice
3331     Rolls-Royce  Phantom Series II  2015   11500.0   Petrol  42500000
12685    Lamborghini               Urus  2021   26000.0   Petrol  39000000
13286  Mercedes-Benz            G-Class  2023    6000.0   Petrol  34800000
10291  Mercedes-Benz            G-Class  2024    3500.0   Diesel  30500000
962            Lexus                 LX  2024   24000.0   Diesel  27750000
331     Aston Martin           Vanquish  2016   25700.0   Petrol  26400000
811    Mercedes-Benz            G-Class  2019   59000.0   Petrol  26000000
5767   Mercedes-Benz            G-Class  2019   59000.0   Petrol  24900000
1187          Toyota       Land Cruiser  2023   15000.0   Diesel  24700000
7435   Mercedes-Benz           SL-Class  2024    1400.0   Petrol  24500000
9241   Mercedes-Benz                AMG  2024   16000.0   Petrol  21500000
5621             BMW           7 Series  2023    7000.0   Petrol  18500000
7615         Bentley        Flying Spur  2017   22000.0   Petrol  18500000
1552           Lexus                 LX  2018   27000.0   Diesel  17500000
9495      Land Rover        Range Rover  2019   29700.0   Diesel  17400000
2152      Land Rover  Range Rover Sport  2023   18650.0   Diesel  16500000
4096      Land Rover        Range Rover  2020   48000.0   Petrol  16500000
7074          Toyota       Land Cruiser  2019   40000.0   Diesel  16500000
9437      Land Rover        Range Rover  2019   55000.0   Petrol  16500000
11534         Toyota            Cruiser  2017   55000.0   Diesel  16500000

Lowest AskPrice:
               Brand           model  Year  kmDriven    FuelType  AskPrice
10352  Maruti Suzuki          Brezza  2023   65200.0      hybrid     15000
13585            BMW        5 Series  2014   90000.0      Diesel     15000
14442        Renault          Duster  2013   80000.0      Diesel     15000
13921  Maruti Suzuki        Alto K10  2021      12.0      hybrid     18000
3034   Maruti Suzuki          Baleno  2024    9000.0      Petrol     18500
14915  Maruti Suzuki     Wagon-R-1-0  2024   55500.0      hybrid     20000
11940       Mahindra       Thar Roxx  2024       0.0      Diesel     21000
14645  Maruti Suzuki          Brezza  2024       0.0      hybrid     29000
13190        Hyundai          Accent  2017   12000.0      hybrid     30000
7507           Ashok   Leyland Stile  2024       0.0  Hybrid/CNG     32000
9134            Tata            Nano  2011   47000.0      Petrol     33000
3906   Mercedes-Benz             GLS  2021  100000.0      Diesel     38000
14025  Maruti Suzuki           Swift  2023   37000.0      Petrol     40000
1878            Tata            Nano  2011   40000.0      Petrol     45000
8171            Tata            Nano  2011      29.0      Petrol     45000
9093             Kia          CERATO  2024       0.0      Diesel     45000
12312         Toyota  Innova Hycross  2023    3000.0      hybrid     48000
5331           Honda            WR-V  2020  650000.0      Diesel     49000
5663   Maruti Suzuki         Wagon R  2020   68000.0      Petrol     49999
3689   Maruti Suzuki      Maruti 800  2013   75893.0      Petrol     50000

In [97]:
df = df[df["kmDriven"] <= 100000].copy()

In [98]:
print("Minimum kmDriven:", df["kmDriven"].min())
print("Maximum kmDriven:", df["kmDriven"].max())

Minimum kmDriven: 0.0
Maximum kmDriven: 100000.0

In [99]:
price_stats = (
    df.groupby("model")["AskPrice"]
    .agg(["count", "min", "median", "max"])
    .sort_values("count", ascending=False)
)

print(price_stats.head(30))

               count      min     median      max
model
Wagon R          505    49999   365000.0   800000
City             385   150000   585000.0  1475000
Ertiga           371    50000   820000.0  1450000
Swift            311    40000   540000.0  1150000
Creta            298   551000   985055.5  2290000
Swift Dzire      290   150000   500000.0   950000
Celerio          280   130000   410500.0   725000
Grand i10        257   110000   429000.0   650000
Baleno           242    18500   583500.0  4999000
Eeco             229   110000   439000.0   878500
i20              188   149000   492500.0  1200500
Verna            187   190000   695000.0  1750000
Amaze            177   249000   515000.0  1125000
i10              176    90000   250000.0   490000
KWID             169   145000   325000.0   670000
Polo             168   150000   580000.0  1300000
Alto 800         163    96000   275000.0   490000
XUV500           153   360000   795000.0  1695000
Ecosport         140   221000   560000.0  1049000
Innova Crysta    138  1100000  2000000.0  3400000
Ciaz             133   261000   600000.0  1000000
Alto K10         127    18000   299000.0   575000
Fortuner         124   985000  3163000.0  4750000
Wagon-R-1-0      120    20000   385000.0   830000
Seltos           116   800000  1390000.0  2250000
Eon              111    98000   240000.0   355000
Vento            105   199000   451000.0   850000
Thar             104   234567  1417500.0  1800000
Tiago            103   260000   495000.0   875000
Jazz             102   199000   495555.5   890000

In [100]:
df[
    df["AskPrice"] < df.groupby("model")["AskPrice"].transform("median") * 0.25
][
    ["Brand", "model", "Year", "Age", "kmDriven",
     "Transmission", "Owner", "FuelType", "AskPrice"]
].sort_values("AskPrice").head(100)

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,AskPrice
13585,BMW,5 Series,2014,10,90000.0,Automatic,second,Diesel,15000
10352,Maruti Suzuki,Brezza,2023,1,65200.0,Automatic,first,hybrid,15000
14442,Renault,Duster,2013,11,80000.0,Manual,second,Diesel,15000
13921,Maruti Suzuki,Alto K10,2021,3,12.0,Automatic,first,hybrid,18000
3034,Maruti Suzuki,Baleno,2024,0,9000.0,Manual,first,Petrol,18500
14915,Maruti Suzuki,Wagon-R-1-0,2024,0,55500.0,Manual,first,hybrid,20000
14645,Maruti Suzuki,Brezza,2024,0,0.0,Automatic,first,hybrid,29000
13190,Hyundai,Accent,2017,7,12000.0,Automatic,first,hybrid,30000
9134,Tata,Nano,2011,13,47000.0,Manual,second,Petrol,33000
3906,Mercedes-Benz,GLS,2021,3,100000.0,Automatic,first,Diesel,38000
14025,Maruti Suzuki,Swift,2023,1,37000.0,Automatic,second,Petrol,40000
12312,Toyota,Innova Hycross,2023,1,3000.0,Automatic,first,hybrid,48000
5663,Maruti Suzuki,Wagon R,2020,4,68000.0,Manual,second,Petrol,49999
14157,Hyundai,Grand i10 Nios,2012,12,98000.0,Manual,first,hybrid,50000
6726,Volkswagen,Ameo,2017,7,83000.0,Automatic,first,Diesel,50000
13762,Maruti Suzuki,Ertiga,2024,0,200.0,Automatic,first,hybrid,50000
14546,Skoda,Rapid,2024,0,10000.0,Automatic,first,hybrid,99090
11879,Audi,Q3 Sportback,2023,1,2200.0,Automatic,first,hybrid,100000
14183,Hyundai,Grand i10 Nios,2023,1,25000.0,Manual,first,hybrid,100000
7380,Maruti Suzuki,Fronx,2024,0,8000.0,Manual,first,Petrol,100000
12094,Maruti Suzuki,Brezza,2024,0,10000.0,Automatic,first,hybrid,100001
9247,Maruti Suzuki,Swift,2011,13,50000.0,Automatic,second,Hybrid/CNG,109999
10094,Hyundai,Aura,2024,0,0.0,Automatic,first,hybrid,120000
12742,Hyundai,Aura,2024,0,0.0,Manual,first,hybrid,125000
14170,Toyota,Corolla Altis,2011,13,92700.0,Manual,second,hybrid,125000
9743,Hyundai,Aura,2024,0,60200.0,Automatic,first,hybrid,150000
6749,Maruti Suzuki,Brezza,2023,1,65200.0,Automatic,first,Hybrid/CNG,150000
2478,Kia,Sonet,2024,0,800.0,Manual,first,Petrol,170000
14823,Tata,Safari,2012,12,85000.0,Manual,second,Diesel,175000
3700,Tata,Safari,2012,12,64000.0,Manual,second,Diesel,197777
13422,Toyota,VELLFIRE,2024,0,0.0,Automatic,first,hybrid,200000
6774,Mahindra,Thar,2024,0,150.0,Automatic,first,Hybrid/CNG,234567
14929,Hyundai,i20 N Line,2021,3,53000.0,Automatic,first,hybrid,250000
6483,Tata,Safari,2011,13,85000.0,Manual,first,Diesel,260000
7257,Tata,Safari,2012,12,79800.0,Manual,second,Diesel,285000
1141,Tata,Safari,2013,11,87312.0,Manual,first,Diesel,349444
9761,Ford,Endeavour,2011,13,95000.0,Manual,second,Diesel,350000
8723,Ford,Endeavour,2011,13,96000.0,Automatic,second,Diesel,351000
6365,Mahindra,Scorpio N,2011,13,48529.0,Manual,second,Diesel,360000
9115,Ford,Endeavour,2014,10,90000.0,Manual,second,Diesel,365000
3299,BMW,X1,2012,12,33000.0,Automatic,first,Diesel,450000
11731,Mercedes-Benz,C-Class,2011,13,85000.0,Automatic,second,Petrol,450000
2857,BMW,5 Series,2011,13,65000.0,Automatic,second,Diesel,525000
2132,BMW,3 Series Gran Limousine,2012,12,51000.0,Automatic,second,Diesel,649000
2830,BMW,5 Series,2011,13,85000.0,Automatic,second,Diesel,650000
9838,Toyota,Innova Hycross,2024,0,1234.0,Manual,first,Petrol,700000
285,BMW,7 Series,2013,11,61000.0,Automatic,second,Diesel,851000
11797,Mercedes-Benz,GLE Class,2014,10,78000.0,Automatic,first,Diesel,985000
11909,Toyota,2.8 Legender 4X2,2021,3,10000.0,Automatic,first,hybrid,1000000
1793,Land Rover,Range Rover Sport,2011,13,73000.0,Automatic,second,Diesel,1850000
11689,Land Rover,Range Rover,2013,11,92000.0,Automatic,second,Diesel,2500000
12413,Mercedes-Benz,G-Class,2016,8,59000.0,Automatic,first,Diesel,2590000

In [101]:
df[
    df["AskPrice"] > df.groupby("model")["AskPrice"].transform("median") * 4
][
    ["Brand", "model", "Year", "Age", "kmDriven",
     "Transmission", "Owner", "FuelType", "AskPrice"]
].sort_values("AskPrice", ascending=False).head(100)

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,AskPrice
5621,BMW,7 Series,2023,1,7000.0,Automatic,first,Petrol,18500000
6508,Mercedes-Benz,E-Class,2021,3,19000.0,Automatic,first,Diesel,7100000
12165,Audi,Q5,2022,2,9000.0,Automatic,first,Petrol,6790000
9328,Mercedes-Benz,E-Class,2021,3,18000.0,Automatic,first,Diesel,6700000
491,Mercedes-Benz,E-Class,2022,2,25000.0,Automatic,first,Diesel,6500000
1231,Tata,Punch,2022,2,7200.0,Manual,first,Petrol,6500000
9612,BMW,3 Series,2022,2,30000.0,Automatic,first,Petrol,5975000
1443,Audi,Q3,2022,2,40000.0,Automatic,first,Petrol,5900000
10126,BMW,3 Series,2022,2,43000.0,Automatic,first,Petrol,5200000
7167,Maruti Suzuki,Baleno,2016,8,31000.0,Automatic,second,Petrol,4999000
717,Honda,Civic,2019,5,20000.0,Automatic,second,Petrol,1773000
1453,Honda,Civic,2020,4,39000.0,Automatic,first,Petrol,1725000
317,Maruti Suzuki,Omni,2014,10,77500.0,Automatic,second,Petrol,1010000
13758,Tata,Nano,2018,6,98000.0,Automatic,first,Diesel,799000

In [102]:
price_check = (
    df.groupby(["model", "Year"])["AskPrice"]
    .agg(
        count="count",
        min_price="min",
        median_price="median",
        max_price="max"
    )
    .reset_index()
)

print(price_check.head(30))

                      model  Year  count  min_price  median_price  max_price
0                  1 Series  2014      1     850000      850000.0     850000
1                  2 Series  2021      1    3490000     3490000.0    3490000
2                  2 Series  2022      2    3765000     3782500.0    3800000
3          2.8 Legender 4X2  2015      1    1450000     1450000.0    1450000
4          2.8 Legender 4X2  2017      1    2500000     2500000.0    2500000
5          2.8 Legender 4X2  2019      1    4000000     4000000.0    4000000
6          2.8 Legender 4X2  2021      6    1000000     3922500.0    4250000
7          2.8 Legender 4X2  2022      4    3985000     4144999.5    5195000
8          2.8 Legender 4X2  2023      2    4195000     4697500.0    5200000
9          2.8 Legender 4X2  2024      2    5495000     5497500.0    5500000
10            2.9 Sportback  2018      1    7500000     7500000.0    7500000
11                   3 DOOR  2015      1    2000000     2000000.0    2000000
12                   3 DOOR  2019      1    3900000     3900000.0    3900000
13                 3 Series  2011      1    1300000     1300000.0    1300000
14                 3 Series  2012     11     571000      721000.0    1250000
15                 3 Series  2013     12     750000     1200000.0    2499000
16                 3 Series  2014      6    1100000     1342500.0    1545000
17                 3 Series  2015      3     915000     1190000.0    2400000
18                 3 Series  2016      4    1325000     1524500.0    1650000
19                 3 Series  2017      1    1550000     1550000.0    1550000
20                 3 Series  2018      3    2399000     2400000.0    3500000
21                 3 Series  2020      4    2850000     3787555.5    4800000
22                 3 Series  2022      3    4100000     5200000.0    5975000
23              3 Series GT  2014      4    1200000     1649500.0    2300000
24              3 Series GT  2015      7    1200000     1545000.0    2500000
25              3 Series GT  2016     11    1490000     1799000.0    2575000
26              3 Series GT  2017      5    1840000     2100000.0    2450000
27              3 Series GT  2018      2    2050000     2070000.0    2090000
28              3 Series GT  2019      5    2550000     3000000.0    3295000
29  3 Series Gran Limousine  2012      1     649000      649000.0     649000

In [103]:
df["model_year_median"] = (
    df.groupby(["model", "Year"])["AskPrice"]
    .transform("median")
)

low_price = df[
    df["AskPrice"] < df["model_year_median"] * 0.30
]

print(
    low_price[
        ["Brand", "model", "Year", "kmDriven",
         "Owner", "Transmission", "FuelType",
         "AskPrice", "model_year_median"]
    ]
    .sort_values("AskPrice")
    .head(100)
)

               Brand             model  Year  kmDriven   Owner Transmission  \
10352  Maruti Suzuki            Brezza  2023   65200.0   first    Automatic
14442        Renault            Duster  2013   80000.0  second       Manual
13585            BMW          5 Series  2014   90000.0  second    Automatic
3034   Maruti Suzuki            Baleno  2024    9000.0   first       Manual
14915  Maruti Suzuki       Wagon-R-1-0  2024   55500.0   first       Manual
14645  Maruti Suzuki            Brezza  2024       0.0   first    Automatic
3906   Mercedes-Benz               GLS  2021  100000.0   first    Automatic
14025  Maruti Suzuki             Swift  2023   37000.0  second    Automatic
12312         Toyota    Innova Hycross  2023    3000.0   first    Automatic
5663   Maruti Suzuki           Wagon R  2020   68000.0  second       Manual
6726      Volkswagen              Ameo  2017   83000.0   first    Automatic
13762  Maruti Suzuki            Ertiga  2024     200.0   first    Automatic
2150            Tata              Nano  2015   34000.0   first       Manual
7380   Maruti Suzuki             Fronx  2024    8000.0   first       Manual
14183        Hyundai    Grand i10 Nios  2023   25000.0   first       Manual
9040         Hyundai         Grand i10  2015   48000.0  second       Manual
9476   Maruti Suzuki           Celerio  2023    1234.0   first       Manual
13110  Maruti Suzuki           Wagon R  2023   43000.0   first       Manual
6749   Maruti Suzuki            Brezza  2023   65200.0   first    Automatic
13537  Maruti Suzuki              Eeco  2023   47000.0   first    Automatic
12428  Maruti Suzuki       Swift Dzire  2022   89000.0  second       Manual
2478             Kia             Sonet  2024     800.0   first       Manual
13613        Hyundai              Aura  2023   40000.0  second    Automatic
6696         Hyundai              Aura  2023    1234.0   first       Manual
13422         Toyota          VELLFIRE  2024       0.0   first    Automatic
5202         Hyundai              Aura  2023   41000.0   first    Automatic
6774        Mahindra              Thar  2024     150.0   first    Automatic
14929        Hyundai        i20 N Line  2021   53000.0   first    Automatic
9838          Toyota    Innova Hycross  2024    1234.0   first       Manual
11909         Toyota  2.8 Legender 4X2  2021   10000.0   first    Automatic

         FuelType  AskPrice  model_year_median
10352      hybrid     15000          1150000.0
14442      Diesel     15000           315499.0
13585      Diesel     15000          1550000.0
3034       Petrol     18500           459250.0
14915      hybrid     20000           280000.0
14645      hybrid     29000           100001.0
3906       Diesel     38000          9575000.0
14025      Petrol     40000           750000.0
12312      hybrid     48000          3597000.0
5663       Petrol     49999           525000.0
6726       Diesel     50000           425000.0
13762      hybrid     50000           780000.0
2150       Petrol     70000           265000.0
7380       Petrol    100000           870000.0
14183      hybrid    100000           700000.0
9040       Diesel    110000           405000.0
9476   Hybrid/CNG    130000           675000.0
13110      hybrid    150000           615000.0
6749   Hybrid/CNG    150000          1150000.0
13537      hybrid    160000           600000.0
12428      hybrid    165000           700000.0
2478       Petrol    170000          1049999.0
13613      hybrid    180000           710000.0
6696   Hybrid/CNG    190000           710000.0
13422      hybrid    200000         12900000.0
5202   Hybrid/CNG    200000           710000.0
6774   Hybrid/CNG    234567          1562500.0
14929      hybrid    250000           915000.0
9838       Petrol    700000          3116000.0
11909      hybrid   1000000          3922500.0

In [104]:
high_price = df[
    df["AskPrice"] > df["model_year_median"] * 3
]

print(
    high_price[
        ["Brand", "model", "Year", "kmDriven",
         "Owner", "Transmission", "FuelType",
         "AskPrice", "model_year_median"]
    ]
    .sort_values("AskPrice", ascending=False)
    .head(100)
)

               Brand        model  Year  kmDriven   Owner Transmission  \
1231            Tata        Punch  2022    7200.0   first       Manual
12933  Mercedes-Benz      C-Class  2015   29000.0  second    Automatic
7167   Maruti Suzuki       Baleno  2016   31000.0  second    Automatic
729    Maruti Suzuki       Brezza  2024   20000.0   first       Manual
317    Maruti Suzuki         Omni  2014   77500.0  second    Automatic
11479  Maruti Suzuki  Swift Dzire  2024    3900.0   first    Automatic

      FuelType  AskPrice  model_year_median
1231    Petrol   6500000           805000.0
12933   Petrol   5800000          1774500.0
7167    Petrol   4999000           521000.0
729     Petrol   1100000           100001.0
317     Petrol   1010000           180000.0
11479   Petrol    928000           280000.0

In [105]:
low_price = df[df["AskPrice"] < 50000]

print(
    low_price[
        ["Brand", "model", "Year", "Age", "kmDriven",
         "Owner", "Transmission", "FuelType", "AskPrice"]
    ].sort_values("AskPrice")
)

               Brand           model  Year  Age  kmDriven   Owner  \
10352  Maruti Suzuki          Brezza  2023    1   65200.0   first
14442        Renault          Duster  2013   11   80000.0  second
13585            BMW        5 Series  2014   10   90000.0  second
13921  Maruti Suzuki        Alto K10  2021    3      12.0   first
3034   Maruti Suzuki          Baleno  2024    0    9000.0   first
14915  Maruti Suzuki     Wagon-R-1-0  2024    0   55500.0   first
11940       Mahindra       Thar Roxx  2024    0       0.0   first
14645  Maruti Suzuki          Brezza  2024    0       0.0   first
13190        Hyundai          Accent  2017    7   12000.0   first
7507           Ashok   Leyland Stile  2024    0       0.0   first
9134            Tata            Nano  2011   13   47000.0  second
3906   Mercedes-Benz             GLS  2021    3  100000.0   first
14025  Maruti Suzuki           Swift  2023    1   37000.0  second
9093             Kia          CERATO  2024    0       0.0   first
8171            Tata            Nano  2011   13      29.0  second
1878            Tata            Nano  2011   13   40000.0  second
12312         Toyota  Innova Hycross  2023    1    3000.0   first
5663   Maruti Suzuki         Wagon R  2020    4   68000.0  second

      Transmission    FuelType  AskPrice
10352    Automatic      hybrid     15000
14442       Manual      Diesel     15000
13585    Automatic      Diesel     15000
13921    Automatic      hybrid     18000
3034        Manual      Petrol     18500
14915       Manual      hybrid     20000
11940    Automatic      Diesel     21000
14645    Automatic      hybrid     29000
13190    Automatic      hybrid     30000
7507     Automatic  Hybrid/CNG     32000
9134        Manual      Petrol     33000
3906     Automatic      Diesel     38000
14025    Automatic      Petrol     40000
9093     Automatic      Diesel     45000
8171     Automatic      Petrol     45000
1878        Manual      Petrol     45000
12312    Automatic      hybrid     48000
5663        Manual      Petrol     49999

In [106]:
high_price = df[df["AskPrice"] > 5000000]

print(
    high_price[
        ["Brand", "model", "Year", "Age", "kmDriven",
         "Owner", "Transmission", "FuelType", "AskPrice"]
    ].sort_values("AskPrice", ascending=False)
)

               Brand              model  Year  Age  kmDriven   Owner  \
3331     Rolls-Royce  Phantom Series II  2015    9   11500.0  second
12685    Lamborghini               Urus  2021    3   26000.0  second
13286  Mercedes-Benz            G-Class  2023    1    6000.0   first
10291  Mercedes-Benz            G-Class  2024    0    3500.0   first
962            Lexus                 LX  2024    0   24000.0   first
...              ...                ...   ...  ...       ...     ...
1290            Audi                 A6  2023    1   11000.0   first
1496            Audi                 A6  2023    1   12000.0   first
5023   Mercedes-Benz            E-Class  2021    3   41000.0   first
3295   Mercedes-Benz          GLC Class  2021    3   15650.0   first
10296  Mercedes-Benz          GLC Class  2021    3   15000.0   first

      Transmission FuelType  AskPrice
3331     Automatic   Petrol  42500000
12685    Automatic   Petrol  39000000
13286    Automatic   Petrol  34800000
10291    Automatic   Diesel  30500000
962      Automatic   Diesel  27750000
...            ...      ...       ...
1290     Automatic   Petrol   5100000
1496     Automatic   Petrol   5100000
5023     Automatic   Diesel   5100000
3295     Automatic   Petrol   5100000
10296    Automatic   Petrol   5100000

[274 rows x 9 columns]

In [107]:
df = df[df["AskPrice"] >= 50000].copy()

In [108]:
df = df[df["kmDriven"] <= 100000].copy()

In [109]:
df.drop(columns=["model_year_median"], inplace=True, errors="ignore")

In [110]:
print("Shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicates:", df.duplicated().sum())

print("\nYear:", df["Year"].min(), "-", df["Year"].max())

print("Age:", df["Age"].min(), "-", df["Age"].max())

print("kmDriven:", df["kmDriven"].min(), "-", df["kmDriven"].max())

print("AskPrice:", df["AskPrice"].min(), "-", df["AskPrice"].max())

Shape: (11008, 11)

Missing values:
Brand           0
model           0
Year            0
Age             0
kmDriven        0
Transmission    0
Owner           0
FuelType        0
AdditionInfo    0
AskPrice        0
model_check     0
dtype: int64

Duplicates: 0

Year: 2011 - 2024
Age: 0 - 13
kmDriven: 0.0 - 100000.0
AskPrice: 50000 - 42500000

In [111]:
df.drop(columns=["model_check"], inplace=True)

In [112]:
print(df.shape)
print(df.columns)

(11008, 10)
Index(['Brand', 'model', 'Year', 'Age', 'kmDriven', 'Transmission', 'Owner',
       'FuelType', 'AdditionInfo', 'AskPrice'],
      dtype='object')

# 4. Feature Engineering

In [113]:
df["kmDrivenPerYear"] = df["kmDriven"] / (df["Age"] + 1)

In [114]:
print(
    df[["Year", "Age", "kmDriven", "kmDrivenPerYear", "AskPrice"]].head(10)
)

    Year  Age  kmDriven  kmDrivenPerYear  AskPrice
3   2017    7   83500.0     10437.500000    565000
4   2019    5   45000.0      7500.000000    685000
5   2014   10   83000.0      7545.454545   1350000
7   2019    5   25000.0      4166.666667   5950000
8   2020    4   33759.0      6751.800000    622000
9   2017    7   69713.0      8714.125000    649000
10  2018    6   70000.0     10000.000000    395000
11  2021    3   25000.0      6250.000000   2900000
12  2012   12   72700.0      5592.307692    240000
14  2021    3   32000.0      8000.000000  11800000

In [115]:
print(df["AdditionInfo"].value_counts(dropna=False).head(30))

print("\nUnique Values:", df["AdditionInfo"].nunique())

print("\nSample Values:")
print(df["AdditionInfo"].head(20))

AdditionInfo
Maruti Suzuki Ertiga 2022-2023 VXI CNG, 2022, CNG & Hybrids               15
Ford Endeavour 3.2 Titanium AT 4X4, 2017, Diesel                          14
Toyota Innova Hycross 2.0 ZX (O) Hybrid 7 STR, 2023, CNG & Hybrids        12
Maruti Suzuki Ertiga 2022-2023 VXI CNG, 2021, CNG & Hybrids               12
Good condition                                                            12
Maruti Suzuki Ertiga VXI CNG, 2017, CNG & Hybrids                         11
Maruti Suzuki Ertiga VXI CNG, 2018, CNG & Hybrids                         11
Maruti Suzuki Ertiga 1.4 VXI CNG Anniversary Edition, 2020, CNG & Hy..    11
Maruti Suzuki Baleno 1.2 Delta AT, 2018, CNG & Hybrids                    10
Honda City VX Petrol CVT, 2016, Petrol                                    10
Volkswagen Polo GT TSI, 2021, Petrol                                      10
Maruti Suzuki Ertiga VXI CNG, 2016, CNG & Hybrids                          9
Renault KWID AMT, 2017, Petrol                                             9
Volkswagen Polo 1.2 GT TSI, 2016, Petrol                                   9
Maruti Suzuki Ertiga 1.4 VXI CNG Anniversary Edition, 2021, CNG & Hy..     8
Maruti Suzuki Ertiga 2012-2015 VXI CNG, 2014, CNG & Hybrids                8
Honda City SV CVT, 2015, CNG & Hybrids                                     8
Maruti Suzuki SX4 Vxi BSIV, 2011, CNG & Hybrids                            8
BMW 3 Series GT 320d Luxury Line, 2016, Diesel                             8
Hyundai Creta 1.6 VTVT AT SX Plus, 2017, Petrol                            8
Mahindra XUV500 W10 AT, 2017, Diesel                                       8
Maruti Suzuki Ciaz Delta Automatic, 2018, CNG & Hybrids                    7
Maruti Suzuki Wagon R 1.0 LXi CNG, 2021, CNG & Hybrids                     7
Maruti Suzuki Wagon R VXI, 2016, Petrol                                    7
Maruti Suzuki Celerio 1.0 VXI AMT, 2016, Petrol                            7
Maruti Suzuki Baleno 1.2 Delta AT, 2017, CNG & Hybrids                     7
Maruti Suzuki Celerio ZXI AMT, 2017, Petrol                                7
Hyundai Grand i10 Nios Sportz, 2020, Petrol                                6
Hyundai i10 Sportz AT, 2012, Petrol                                        6
Hyundai i10 1.2 Kappa Magna, 2011, Petrol                                  6
Name: count, dtype: int64

Unique Values: 8467

Sample Values:
3        Maruti Suzuki Swift 2017 Diesel Good Condition
4          Maruti Suzuki Baleno Alpha CVT, 2019, Petrol
5                   BMW X3 2.0 XDRIVE 20D, 2014, Diesel
7           BMW 5 Series 3.0 530D M Sport, 2019, Diesel
8             Maruti Suzuki Dzire 1.2 VXI, 2020, Petrol
9     Ford Ecosport 1.5 Ti VCT MT Titanium BE, 2017,...
10      Maruti Suzuki Alto K10 VXI Airbag, 2018, Petrol
11             Kia Carnival Premium 8 STR, 2021, Diesel
12      Maruti Suzuki Swift Dzire VXI 1.2, 2012, Petrol
14    Mercedes-Benz GLE COUPE 3.0 53 AMG 4MATIC Plus...
16                  Kia Seltos HTK Plus D, 2020, Diesel
17          Maruti Suzuki Ertiga VDI SHVS, 2016, Diesel
18     Maruti Suzuki Ertiga 2017 Petrol 59000 Km Driven
19       BMW 3 Series GT 320d Luxury Line, 2015, Diesel
20     Ford Endeavour 2.2 Titanium AT 4X2, 2019, Diesel
23          Audi A3 2.0 35 TDI Attraction, 2015, Diesel
24    Renault KWID RXT AMT Climber (Automatic), 2019...
25                              MG Hector, 2019, Petrol
26     Maruti Suzuki Swift Dzire Vdi BSIV, 2012, Diesel
27    Maruti Suzuki Celerio 2014-2017 VXI AT, 2014, ...
Name: AdditionInfo, dtype: object

In [116]:
df["AdditionInfo_lower"] = df["AdditionInfo"].astype(str).str.lower()

df["GoodCondition"] = df["AdditionInfo_lower"].str.contains(
    "good condition", 
    na=False
).astype(int)

print(df["GoodCondition"].value_counts())

GoodCondition
0    10724
1      284
Name: count, dtype: int64

In [117]:
print(df[["AdditionInfo", "GoodCondition"]].head(20))

print("\nGood Condition Count:")
print(df["GoodCondition"].value_counts())

                                         AdditionInfo  GoodCondition
3      Maruti Suzuki Swift 2017 Diesel Good Condition              1
4        Maruti Suzuki Baleno Alpha CVT, 2019, Petrol              0
5                 BMW X3 2.0 XDRIVE 20D, 2014, Diesel              0
7         BMW 5 Series 3.0 530D M Sport, 2019, Diesel              0
8           Maruti Suzuki Dzire 1.2 VXI, 2020, Petrol              0
9   Ford Ecosport 1.5 Ti VCT MT Titanium BE, 2017,...              0
10    Maruti Suzuki Alto K10 VXI Airbag, 2018, Petrol              0
11           Kia Carnival Premium 8 STR, 2021, Diesel              0
12    Maruti Suzuki Swift Dzire VXI 1.2, 2012, Petrol              0
14  Mercedes-Benz GLE COUPE 3.0 53 AMG 4MATIC Plus...              0
16                Kia Seltos HTK Plus D, 2020, Diesel              0
17        Maruti Suzuki Ertiga VDI SHVS, 2016, Diesel              0
18   Maruti Suzuki Ertiga 2017 Petrol 59000 Km Driven              0
19     BMW 3 Series GT 320d Luxury Line, 2015, Diesel              0
20   Ford Endeavour 2.2 Titanium AT 4X2, 2019, Diesel              0
23        Audi A3 2.0 35 TDI Attraction, 2015, Diesel              0
24  Renault KWID RXT AMT Climber (Automatic), 2019...              0
25                            MG Hector, 2019, Petrol              0
26   Maruti Suzuki Swift Dzire Vdi BSIV, 2012, Diesel              0
27  Maruti Suzuki Celerio 2014-2017 VXI AT, 2014, ...              0

Good Condition Count:
GoodCondition
0    10724
1      284
Name: count, dtype: int64

In [118]:
df["AdditionInfo_lower"] = df["AdditionInfo"].astype(str).str.lower()

df["Info_Automatic"] = df["AdditionInfo_lower"].str.contains(
    r"\b(automatic|amt|cvt|dct|at)\b",
    regex=True,
    na=False
).astype(int)

df["Info_Manual"] = df["AdditionInfo_lower"].str.contains(
    r"\b(manual|mt)\b",
    regex=True,
    na=False
).astype(int)

print(df[["AdditionInfo", "Info_Automatic", "Info_Manual"]].head(30))

print("\nAutomatic:")
print(df["Info_Automatic"].value_counts())

print("\nManual:")
print(df["Info_Manual"].value_counts())

                                         AdditionInfo  Info_Automatic  \
3      Maruti Suzuki Swift 2017 Diesel Good Condition               0
4        Maruti Suzuki Baleno Alpha CVT, 2019, Petrol               1
5                 BMW X3 2.0 XDRIVE 20D, 2014, Diesel               0
7         BMW 5 Series 3.0 530D M Sport, 2019, Diesel               0
8           Maruti Suzuki Dzire 1.2 VXI, 2020, Petrol               0
9   Ford Ecosport 1.5 Ti VCT MT Titanium BE, 2017,...               0
10    Maruti Suzuki Alto K10 VXI Airbag, 2018, Petrol               0
11           Kia Carnival Premium 8 STR, 2021, Diesel               0
12    Maruti Suzuki Swift Dzire VXI 1.2, 2012, Petrol               0
14  Mercedes-Benz GLE COUPE 3.0 53 AMG 4MATIC Plus...               0
16                Kia Seltos HTK Plus D, 2020, Diesel               0
17        Maruti Suzuki Ertiga VDI SHVS, 2016, Diesel               0
18   Maruti Suzuki Ertiga 2017 Petrol 59000 Km Driven               0
19     BMW 3 Series GT 320d Luxury Line, 2015, Diesel               0
20   Ford Endeavour 2.2 Titanium AT 4X2, 2019, Diesel               1
23        Audi A3 2.0 35 TDI Attraction, 2015, Diesel               0
24  Renault KWID RXT AMT Climber (Automatic), 2019...               1
25                            MG Hector, 2019, Petrol               0
26   Maruti Suzuki Swift Dzire Vdi BSIV, 2012, Diesel               0
27  Maruti Suzuki Celerio 2014-2017 VXI AT, 2014, ...               1
29  Toyota Fortuner Legender 4X4 AT 2.8, 2023, Diesel               1
30     Toyota Innova Crysta 2.4 V 8 STR, 2017, Diesel               0
31           Toyota Innova 2.5 VX 8 STR, 2011, Diesel               0
32             Volvo S90 D4 Inscription, 2018, Diesel               0
33                      Hyundai Venue E, 2021, Petrol               0
34      Maruti Suzuki Ertiga VXI Petrol, 2018, Petrol               0
35  Creta Top model Night Edition 2023 Petrol Well...               0
36                      Hyundai Alcazar, 2022, Diesel               0
37               Hyundai i20 Magna Plus, 2019, Petrol               0
39  Volkswagen Polo 1.0 Comfortline Plus, 2021, Pe...               0

    Info_Manual
3             0
4             0
5             0
7             0
8             0
9             1
10            0
11            0
12            0
14            0
16            0
17            0
18            0
19            0
20            0
23            0
24            0
25            0
26            0
27            0
29            0
30            0
31            0
32            0
33            0
34            0
35            0
36            0
37            0
39            0

Automatic:
Info_Automatic
0    8518
1    2490
Name: count, dtype: int64

Manual:
Info_Manual
0    10568
1      440
Name: count, dtype: int64

C:\Users\Dell\AppData\Local\Temp\ipykernel_16776\506147244.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df["Info_Automatic"] = df["AdditionInfo_lower"].str.contains(
C:\Users\Dell\AppData\Local\Temp\ipykernel_16776\506147244.py:9: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df["Info_Manual"] = df["AdditionInfo_lower"].str.contains(

In [119]:
df.drop(
    columns=["Info_Automatic", "Info_Manual"],
    inplace=True
)

In [120]:
df.drop(columns=["AdditionInfo_lower"], inplace=True)

In [121]:
print(df.columns)
print(df.shape)

Index(['Brand', 'model', 'Year', 'Age', 'kmDriven', 'Transmission', 'Owner',
       'FuelType', 'AdditionInfo', 'AskPrice', 'kmDrivenPerYear',
       'GoodCondition'],
      dtype='object')
(11008, 12)

In [122]:
print(df[["kmDriven", "AskPrice", "kmDrivenPerYear"]].skew())

kmDriven          -0.361535
AskPrice           7.966241
kmDrivenPerYear    2.323563
dtype: float64

In [123]:
print(df[["kmDriven", "AskPrice", "kmDrivenPerYear"]].describe())

            kmDriven      AskPrice  kmDrivenPerYear
count   11008.000000  1.100800e+04     11008.000000
mean    56416.153525  1.089113e+06      8269.082370
std     25012.346004  1.728740e+06      4634.870757
min         0.000000  5.000000e+04         0.000000
25%     39000.000000  3.950000e+05      5538.461538
50%     59974.000000  6.000000e+05      7497.625000
75%     75215.750000  1.086250e+06     10000.000000
max    100000.000000  4.250000e+07     65200.000000

In [124]:
import numpy as np

df["Log_AskPrice"] = np.log1p(df["AskPrice"])

print(df[["AskPrice", "Log_AskPrice"]].head(10))

    AskPrice  Log_AskPrice
3     565000     13.244583
4     685000     13.437176
5    1350000     14.115616
7    5950000     15.598902
8     622000     13.340697
9     649000     13.383190
10    395000     12.886644
11   2900000     14.880222
12    240000     12.388398
14  11800000     16.283610

In [125]:
print(df["Log_AskPrice"].describe())
print("\nSkewness:")
print(df["Log_AskPrice"].skew())

count    11008.000000
mean        13.442120
std          0.854617
min         10.819798
25%         12.886644
50%         13.304687
75%         13.898241
max         17.565015
Name: Log_AskPrice, dtype: float64

Skewness:
0.7357484257631545

In [126]:
print("kmDriven skewness:", df["kmDriven"].skew())
print("kmDrivenPerYear skewness:", df["kmDrivenPerYear"].skew())

kmDriven skewness: -0.3615345279716442
kmDrivenPerYear skewness: 2.3235627774820253

In [127]:
df["Log_kmDrivenPerYear"] = np.log1p(df["kmDrivenPerYear"])

print(df[["kmDrivenPerYear", "Log_kmDrivenPerYear"]].head(10))

print("\nOriginal skewness:",
      df["kmDrivenPerYear"].skew())

print("Log skewness:",
      df["Log_kmDrivenPerYear"].skew())

    kmDrivenPerYear  Log_kmDrivenPerYear
3      10437.500000             9.253256
4       7500.000000             8.922792
5       7545.454545             8.928833
7       4166.666667             8.335112
8       6751.800000             8.817713
9       8714.125000             9.072815
10     10000.000000             9.210440
11      6250.000000             8.740497
12      5592.307692             8.629326
14      8000.000000             8.987322

Original skewness: 2.3235627774820253
Log skewness: -5.455293594923949

In [128]:
df.drop(columns=["Log_kmDrivenPerYear"], inplace=True)

In [129]:
print(df.columns)

Index(['Brand', 'model', 'Year', 'Age', 'kmDriven', 'Transmission', 'Owner',
       'FuelType', 'AdditionInfo', 'AskPrice', 'kmDrivenPerYear',
       'GoodCondition', 'Log_AskPrice'],
      dtype='object')

In [130]:
# Code 1: Categorical columns
categorical_cols = [
    "Brand",
    "model",
    "Transmission",
    "Owner",
    "FuelType"
]

print(categorical_cols)

['Brand', 'model', 'Transmission', 'Owner', 'FuelType']

In [131]:
# Code 3: Top categories
for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts().head(10))

--- Brand ---
Brand
Maruti Suzuki    3490
Hyundai          1891
Honda             866
Toyota            604
Mahindra          570
Tata              474
Mercedes-Benz     448
Volkswagen        356
BMW               331
Renault           318
Name: count, dtype: int64

--- model ---
model
Wagon R        504
City           385
Ertiga         371
Swift          310
Creta          298
Swift Dzire    290
Celerio        280
Grand i10      257
Baleno         241
Eeco           229
Name: count, dtype: int64

--- Transmission ---
Transmission
Automatic    5689
Manual       5319
Name: count, dtype: int64

--- Owner ---
Owner
first     5952
second    5056
Name: count, dtype: int64

--- FuelType ---
FuelType
Petrol        4551
Diesel        3498
hybrid        1502
Hybrid/CNG    1457
Name: count, dtype: int64

In [132]:
# Code 4: Current dataset information
print("Shape:", df.shape)
print("\nData Types:")
print(df.dtypes)

Shape: (11008, 13)

Data Types:
Brand               object
model               object
Year                 int64
Age                  int64
kmDriven           float64
Transmission        object
Owner               object
FuelType            object
AdditionInfo        object
AskPrice             int64
kmDrivenPerYear    float64
GoodCondition        int64
Log_AskPrice       float64
dtype: object

In [133]:
# Code 1: Age groups create karo
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[-1, 2, 5, 10, float("inf")],
    labels=["New", "Mid", "Old", "Very Old"]
)

In [134]:
# Code 2: AgeGroup distribution check karo
print(df["AgeGroup"].value_counts().sort_index())

AgeGroup
New         1513
Mid         2633
Old         5274
Very Old    1588
Name: count, dtype: int64

In [135]:
# Code 3: Age ke saath AgeGroup verify karo
print(df[["Year", "Age", "AgeGroup"]].head(20))

    Year  Age  AgeGroup
3   2017    7       Old
4   2019    5       Mid
5   2014   10       Old
7   2019    5       Mid
8   2020    4       Mid
9   2017    7       Old
10  2018    6       Old
11  2021    3       Mid
12  2012   12  Very Old
14  2021    3       Mid
16  2020    4       Mid
17  2016    8       Old
18  2017    7       Old
19  2015    9       Old
20  2019    5       Mid
23  2015    9       Old
24  2019    5       Mid
25  2019    5       Mid
26  2012   12  Very Old
27  2014   10       Old

In [136]:
# Code 4: Missing check
print("AgeGroup missing:", df["AgeGroup"].isna().sum())
print("Unique AgeGroups:", df["AgeGroup"].nunique())

AgeGroup missing: 0
Unique AgeGroups: 4

# 5. Feature Selections

In [137]:
X = df.drop(columns=["AskPrice", "Year", "AdditionInfo"])
y = df["AskPrice"]

In [138]:
print(X.columns)
print("Target:", y.name)

Index(['Brand', 'model', 'Age', 'kmDriven', 'Transmission', 'Owner',
       'FuelType', 'kmDrivenPerYear', 'GoodCondition', 'Log_AskPrice',
       'AgeGroup'],
      dtype='object')
Target: AskPrice

In [139]:
X = df.drop(columns=["AskPrice", "Year", "AdditionInfo"], errors="ignore")
X = X.drop(columns=["Log_AskPrice"], errors="ignore")

y = df["AskPrice"]

print(X.columns.tolist())

['Brand', 'model', 'Age', 'kmDriven', 'Transmission', 'Owner', 'FuelType', 'kmDrivenPerYear', 'GoodCondition', 'AgeGroup']

# 6. Train-Test Split

In [140]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (8806, 10)
X_test : (2202, 10)
y_train: (8806,)
y_test : (2202,)

In [141]:
print(X.columns.tolist())

['Brand', 'model', 'Age', 'kmDriven', 'Transmission', 'Owner', 'FuelType', 'kmDrivenPerYear', 'GoodCondition', 'AgeGroup']

# 7. Data Preprocessing

In [142]:
categorical_cols = [
    "Brand", "model", "Transmission",
    "Owner", "FuelType", "AgeGroup"
]

numerical_cols = [
    "Age", "kmDriven",
    "kmDrivenPerYear", "GoodCondition"
]

In [143]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ],
    remainder="passthrough"
)

In [144]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("X_train:", X_train_processed.shape)
print("X_test :", X_test_processed.shape)

X_train: (8806, 407)
X_test : (2202, 407)

# 8. Models Training

## 8.1 Linear Regression

In [145]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train_processed, y_train)

LinearRegression()

# Prediction

In [146]:
y_pred = model.predict(X_test_processed)

print(y_pred[:5])

[2519478.47651914  760979.73264375 -156492.52234086  644150.53368177
  786632.47340345]

# Evaluation

In [147]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

MAE : 513539.8494859963
RMSE: 1246495.9530123107
R²  : 0.4954189034909888

In [148]:
print("Train R²:", model.score(X_train_processed, y_train))
print("Test R² :", model.score(X_test_processed, y_test))

Train R²: 0.560273021447031
Test R² : 0.4954189034909888

## 8.2 Decision Tree

In [149]:
from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor(
    random_state=42,
    max_depth=15
)

dt_model.fit(X_train_processed, y_train)

DecisionTreeRegressor(max_depth=15, random_state=42)

# Prection

In [150]:
y_pred_dt = dt_model.predict(X_test_processed)

print(y_pred_dt[:5])

[1756805.50176678  481421.48936642  481421.48936642  836077.04012768
  890392.47619048]

# Evaluation

In [151]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("Train R²:", dt_model.score(X_train_processed, y_train))
print("Test R² :", dt_model.score(X_test_processed, y_test))

print("MAE :", mean_absolute_error(y_test, y_pred_dt))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_dt)))
print("R²  :", r2_score(y_test, y_pred_dt))

Train R²: 0.944747149548696
Test R² : 0.5607728153164625
MAE : 368915.46949647664
RMSE: 1162973.959867021
R²  : 0.5607728153164625

## 8.3 Random Forest Regressor

In [152]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train_processed, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

# Prediction + Evaluation

In [153]:
y_pred_rf = rf_model.predict(X_test_processed)

print("Train R²:", rf_model.score(X_train_processed, y_train))
print("Test R² :", rf_model.score(X_test_processed, y_test))

print("MAE :", mean_absolute_error(y_test, y_pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))
print("R²  :", r2_score(y_test, y_pred_rf))

Train R²: 0.9661525731082242
Test R² : 0.674052054823645
MAE : 198514.5116781201
RMSE: 1001842.6318924971
R²  : 0.674052054823645

# 10. Hyperparameter Tuning

In [154]:
from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    "n_estimators": [50, 100, 150],
    "max_depth": [10, 15, 20, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2"]
}

rf_tuning = RandomizedSearchCV(
    estimator=RandomForestRegressor(random_state=42, n_jobs=-1),
    param_distributions=param_grid,
    n_iter=10,
    cv=3,
    scoring="r2",
    random_state=42,
    n_jobs=-1
)

rf_tuning.fit(X_train_processed, y_train)

RandomizedSearchCV(cv=3,
                   estimator=RandomForestRegressor(n_jobs=-1, random_state=42),
                   n_jobs=-1,
                   param_distributions={'max_depth': [10, 15, 20, None],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [50, 100, 150]},
                   random_state=42, scoring='r2')

# Best parameters dekho

In [155]:
print("Best Parameters:", rf_tuning.best_params_)
print("Best CV R²:", rf_tuning.best_score_)

Best Parameters: {'n_estimators': 50, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
Best CV R²: 0.5932829894419341

# rf_tuning.best_estimator_ ko test data par evaluate karenge

In [156]:
best_rf = rf_tuning.best_estimator_

y_pred_tuned = best_rf.predict(X_test_processed)

print("Train R²:", best_rf.score(X_train_processed, y_train))
print("Test R² :", best_rf.score(X_test_processed, y_test))

print("MAE :", mean_absolute_error(y_test, y_pred_tuned))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_tuned)))
print("R²  :", r2_score(y_test, y_pred_tuned))

Train R²: 0.8191261763243189
Test R² : 0.5639513954205705
MAE : 364569.8573404247
RMSE: 1158758.2394064139
R²  : 0.5639513954205705

# 11. Final Model: Selection

In [157]:
final_model = rf_model

# 12. Final Model Training & Saving

In [158]:
# 1. Final model select karo
final_model = rf_model


# 2. Model save karne ke liye joblib import karo
import joblib
import os


# 3. Final Random Forest model save karo
joblib.dump(final_model, "used_car_price_model.pkl")


# 4. Preprocessor save karo
joblib.dump(preprocessor, "used_car_preprocessor.pkl")


# 5. Check karo files successfully save hui ya nahi
print("Model saved:", os.path.exists("used_car_price_model.pkl"))
print("Preprocessor saved:", os.path.exists("used_car_preprocessor.pkl"))

Model saved: True
Preprocessor saved: True

# 13. New Car Price Prediction

In [159]:
import joblib

final_model = joblib.load("used_car_price_model.pkl")
preprocessor = joblib.load("used_car_preprocessor.pkl")

In [160]:
new_car = pd.DataFrame({
    "Brand": ["Maruti"],
    "model": ["Swift"],
    "Age": [3],
    "kmDriven": [30000],
    "Transmission": ["Manual"],
    "Owner": ["first"],
    "FuelType": ["Petrol"],
    "kmDrivenPerYear": [10000],
    "GoodCondition": [1],
    "AgeGroup": ["2-5"]
})

In [161]:
new_car_processed = preprocessor.transform(new_car)

In [162]:
predicted_price = final_model.predict(new_car_processed)

print("Predicted Car Price: ₹", round(predicted_price[0], 2))

Predicted Car Price: ₹ 785589.97